### PR TITLE
Update logos (Sielte, Lepida)

### PR DESCRIPTION
**Pull request by damikael**

### CODE REVIEW

**Comment by bfabio** [comment]
Sielte's logo is really small:

image

**Comment by libremente** [comment]
Ping @damikael, thanks!

**Comment by libremente** [comment]
@damikael any news on this? Thank you!

**Comment by damikael** [comment]
@libremente commit updated. Please review, thanks

**Review by bfabio — APPROVED** [review]
Looks good, thanks @damikael :+1:

**Pull request merged**
